prog3_BAT0MD/ComicsMovies.Web/Models/Director.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ComicsMovies.Web.Models
{
    public class Director
    {
        [Display(Name = "Director ID")]
        [Required]
        public int Id { get; set; }

        [Display(Name = "First Name")]
        [Required]
        [StringLength(30, MinimumLength = 5)]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required]
        [StringLength(30, MinimumLength = 5)]
        public string LastName { get; set; }

        [Display(Name = "Nationality")]
        [Required]
        public string Nationality { get; set; }

        [Display(Name = "Birth")]
        [Required]
        public string Birth { get; set; }

        [Display(Name = "Salary")]
        [Required]
        public int Salary { get; set; }
    }
}

prog3_BAT0MD/ComicsMovies.Web/Models/DirectorsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicsMovies.Web.Models
{
    public class DirectorsViewModel
    {
        public Director EditedDirector { get; set; }
        public List<Director> ListOfDirectors { get; set; }
    }
}

prog3_BAT0MD/ComicsMovies.Web/Controllers/DirectorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ComicsMovies.Logic;
using ComicsMovies.Web.Models;
using AutoMapper;
using ComicsMovies.Repository;
using ComicsMovies.Data;

namespace ComicsMovies.Web.Controllers
{
    public class DirectorsController : Controller
    {
        ILogic logic;
        IMapper mapper;
        DirectorsViewModel vm;

        public DirectorsController()
        {
            ComicsMoviesDatabaseEntities cmde = new ComicsMoviesDatabaseEntities();
            DirectorRepository dirRepo = new DirectorRepository(cmde);
            logic = new ComicsLogic(dirRepo);
            mapper = MapperFactory.CreateMapper();

            vm = new DirectorsViewModel();
            vm.EditedDirector = new Director();
            var directors = logic.GetAllDirectors();
            vm.ListOfDirectors = mapper.Map<IList<Data.rendezo>, List<Models.Director>>(directors);
        }

        private Director GetDirectorModel(int id)
        {
            rendezo oneDirector = logic.GetOneDirector(id);
            return mapper.Map<Data.rendezo, Models.Director>(oneDirector);
        }

        // GET: Directors
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("DirectorIndex", vm);
        }

        // GET: Directors/Details/5
        public ActionResult Details(int id)
        {
            return View("DirectorDetails", GetDirectorModel(id));
        }

        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete fail";
            if (logic.Remove_Director(id)) TempData["editResult"] = "Delete OK";
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedDirector = GetDirectorModel(id);
            return View("DirectorIndex", vm);
        }

        [HttpPost]
        public ActionResult Edit(Director dir, string editAction)
        {
            if(ModelState.IsValid && dir != null)
            {
                TempData["editResult"] = "Edit OK";
                if(editAction == "AddNew")
                {
                    logic.Add_Director(dir.FirstName, dir.LastName, dir.Nationality, dir.Birth, dir.Salary);
                }
                else
                {
                    bool success = logic.ChangeDirector(dir.Id,dir.FirstName,dir.LastName,dir.Birth,dir.Nationality,dir.Salary);
                    if (!success) TempData["editResult"] = "EDIT fail";
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedDirector = dir;
                return View("DirectorIndex", vm);
            }
        }
    }
}

prog3_BAT0MD/ComicsMovies.Web/Views/Directors/DirectorDetails.cshtml
@model  ComicsMovies.Web.Models.Director
@{
    ViewBag.Title = "DirectorDetails";
}

<h2>Datasheet of one director</h2>
@Html.ActionLink("Back to the list", "Index")

<table>
    <tr>
        <td>The ID for the director</td>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.FirstName)</td>
        <td>@Html.DisplayFor(m => m.FirstName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.LastName)</td>
        <td>@Html.DisplayFor(m => m.LastName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Nationality)</td>
        <td>@Html.DisplayFor(m => m.Nationality)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Salary)</td>
        <td>@Html.DisplayFor(m => m.Salary)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Birth)</td>
        <td>@Html.DisplayFor(m => m.Birth)</td>
    </tr>
</table>

prog3_BAT0MD/ComicsMovies.Web/Views/Directors/DirectorEdit.cshtml
@model ComicsMovies.Web.Models.Director

<h2>Edit one director</h2>

@using (Html.BeginForm("Edit", "Directors"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id);
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.FirstName)</div>
    <div class="editor-field">@Html.EditorFor(m => m.FirstName)</div>

    <div class="editor-label">@Html.LabelFor(m => m.LastName)</div>
    <div class="editor-field">@Html.EditorFor(m => m.LastName)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Nationality)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Nationality)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Salary)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Salary)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Birth)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Birth)</div>

    <input type="submit" value="SEND"/>
}

prog3_BAT0MD/ComicsMovies.Web/Views/Directors/DirectorIndex.cshtml
@model ComicsMovies.Web.Models.DirectorsViewModel
@{
    ViewBag.Title = "DirectorIndex";
}

<h2>Directors Index</h2>

<p style="color:red; font-weight: bold">@TempData["editResult"]</p>

@Html.Partial("DirectorEdit", Model.EditedDirector)
@Html.Partial("DirectorList", Model.ListOfDirectors)

prog3_BAT0MD/ComicsMovies.Web/Views/Directors/DirectorList.cshtml
@model IEnumerable<ComicsMovies.Web.Models.Director>

<h2>List of directors</h2>

@if(Model.Count() == 0)
{
    <p>No data in the database.</p>
}
else
{
        <table border="1">
            <tr>
                <th>@Html.DisplayNameFor(m => m.First().FirstName)</th>
                <th>@Html.DisplayNameFor(m => m.First().LastName)</th>
                <th>Datasheet</th>
                <th>Delete</th>
                <th>Edit</th>
            </tr>
            @foreach (var item in Model)
            {
            <tr>
                <td>@Html.DisplayFor(m => item.FirstName)</td>
                <td>@Html.DisplayFor(m => item.LastName)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.Id })</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.Id })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.Id })</td>
            </tr>
            }
        </table>
}